services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: vive-silver-admin
    restart: always
    networks:
      - proxy
  proveedor:
    build:
      context: ./proveedor
      dockerfile: Dockerfile
    container_name: vive-silver-proveedor
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true
